// table schema generated by introspection
import { pgEnum, pgTable, serial, timestamp, uuid, varchar } from 'drizzle-orm/pg-core'

export const userRoleEnum = pgEnum('user_role', ['MANAGER', 'CUSTOMER', 'ADMIN'])

export const user = pgTable('tb_users', {
  id: uuid('id').primaryKey().$defaultFn(() => Bun.randomUUIDv7()),
  internalId: serial('internal_id').notNull().unique(),
  role: userRoleEnum('role').notNull().default('CUSTOMER'),
  name: varchar({ length: 255 }),
  phone: varchar({ length: 20 }).notNull().unique(),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedAt: timestamp('updated_at').notNull().defaultNow()
})
