// table schema generated by introspection
import { pgTable, varchar, timestamp } from 'drizzle-orm/pg-core'

export const vehicleModel = pgTable('tb_vehicle_models', {
  code: varchar('code').notNull().primaryKey(),
  name: varchar('name').notNull(),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedAt: timestamp('updated_at').notNull().defaultNow()
})
