// table schema generated by introspection
import { jsonb, pgTable, timestamp, uuid, varchar } from 'drizzle-orm/pg-core'

export const vehicleDetail = pgTable('tb_vehicle_details', {
  id: uuid('id').primaryKey().$defaultFn(() => Bun.randomUUIDv7()),
  brand: varchar('brand').notNull(),
  codeFipe: varchar('code_fipe').notNull(),
  fuel: varchar('fuel').notNull(),
  fuelAcronym: varchar('fuel_acronym').notNull(),
  model: varchar('model').notNull(),
  modelYear: varchar('model_year').notNull(),
  price: varchar('price').notNull(),
  priceHistory: jsonb('price_history'),
  referenceMonth: varchar('reference_month').notNull(),
  vehicleType: varchar('vehicle_type').notNull(),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedAt: timestamp('updated_at').notNull().defaultNow()
})
