// table schema generated by introspection
import { pgTable, timestamp, varchar } from 'drizzle-orm/pg-core'

export const vehicleBrand = pgTable('tb_vehicle_brands', {
  code: varchar('code').notNull().primaryKey(),
  name: varchar('name').notNull(),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedAt: timestamp('updated_at').notNull().defaultNow()
})
